---
galaxy_role_file: requirements.yml
# galaxy_roles_path: ~/.ansible/roles
# debug: true

# Load balancer server defaults.
lb_serve_defaults: &lb_server
  name: devbox_lb
  hostname: devbox-lb
  group: devbox_lb
  forward_ports:
  - guest: 80
    host: 8000
  - guest: 443
    host: 44300

# Application server defaults.
www_server_defaults: &www_server
  name: devbox_www
  hostname: devbox-www
  group: devbox_www
  forward_ports:
  - guest: 80
    host: 8000
  folders:
  - map: ./public
    to: /var/www/public
    owner: root
    group: www-data
    dmode: 775
    fmode: 664
    create: true

# Database server defaults.
db_serve_defaults: &db_server
  name: devbox_db
  hostname: devbox-db
  group: devbox_db
  forward_ports:
  - guest: 3306
    host: 33060
  os: ubuntu
  os_version: '18.04'
  cpus: 2
  memory: 4096

# Servers to configure.
servers:
- <<: *lb_server
  ip: '192.168.2.41'
- <<: *www_server
  ip: '192.168.2.42'
- <<: *www_server
  ip: '192.168.2.43'
- <<: *db_server
  ip: '192.168.2.44'